name: php-composer-app
services:
    phpapp:
        build:
            dockerfile: ./Dockerfile
            args:
                MYSQL_CLIENT: mariadb-client
            context: .
        # entrypoint: ["entrypoint"]
        command: > 
            sh -c "cd /var/www/html/app/ &&
                    composer i &&
                    composer run start;"
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - phpnet
        depends_on:
            - mariadb
    mariadb:
        image: 'mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'volmariadb:/var/lib/mysql'
        networks:
            - phpnet
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
          - '${FORWARD_MYADMIN_PORT:-8093}:80'
        environment:
            PMA_HOST: 'mariadb'
        networks:
            - phpnet
        depends_on:
            - mariadb
networks:
    phpnet:
        driver: bridge
volumes:
    volmariadb:
        driver: local